---
# Upgrade ceph cluster properly
# * Preparations
# * Upgrade monitors one by one
# * Upgrade OSDs one by one

# Preparations:
# - install helper tools
# - configure repositories
# - synchronize time
# - download the packages

- hosts:
    - mons
    - osds
    - clients
    - rgws
  become: True
  pre_tasks:
    - name: install pre-dependencies
      package: >
        name={{ item }}
        state=present
      with_items:
        - "python-pycurl"
        - hdparm
        - ntp
        - "python-apt"

    - include: ./tasks/timesync.yml
      when: "{{ do_time_sync|default(False)|bool }}"

    - include: ./tasks/aptrepos.yml
      tags: apt_conf

    - include: ./tasks/packages_version_check_p1.yml


# note: version check completes here since all hostvars have been populated
# on previous step

- hosts:
    - mons
    - osds
    - clients
    - rgws
  become: True
  tasks:
    - include: ./tasks/packages_version_check_p2.yml
      when: "{{ not(skip_package_version_check|default(False)|bool) }}"

    - include: ./tasks/grab_packages.yml

- hosts: mons
  become: True
  serial: 1
  tasks:
    - include: ./tasks/install_upgrade_packages.yml
    - name: find out currently running mon version
      command: >
        ceph daemon mon.{{ inventory_hostname_short }} version
      register: running_mon_version
    - include: ./tasks/restart_mons.yml
      when:
        - "{{ (running_mon_version.stdout|from_json).version != ceph_candidate_package_version.stdout }}"
  vars:
    mon_restart_delay: 5
    mon_restart_attempts: 20


# Upgrade OSDs. On each OSD node
# - Upgrade/install ceph packages
# - Set flags to prevent data rebalancing
# - Restart OSDs on the node
# - Wait for recovery to complete
# - Proceed to the next node

- hosts: osds
  become: True
  serial: 1
  tasks:
    - include: ./tasks/install_upgrade_packages.yml
    - include: ./tasks/restart_osds.yml


# Upgrade ceph clients (hypervisor nodes).
# - Install/upgrade ceph packages
# - TODO: Restart processes using ceph client libraries

- hosts: clients
  become: True
  tasks:
    - include: ./tasks/install_upgrade_packages.yml

